# 权限不足时提示
NO-PERMISSION-MESSAGE: '&f&l(&4&l？&f&l) &c你没有权利这么做'
# 不满足条件时提示
NO-CLAIM-MESSAGE: '&f&l(&4&l？&f&l) &c你现在还不能这么做 &7(%s%&7)'

# 数据储存地址
# 该配置将在启用数据库储存时失效
DATAURL:
  # 玩家数据
  PLAYER-DATA: 'plugins/TabooLib/playerdata/'
  # 插件数据
  SERVER-DATA: 'plugins/TabooLib/serverdata/'
  # 物品数据（来自 ItemSave 插件）
  ITEMDIR: 'plugins/Skript/scripts/config/item.yml'

# 语言文件相关设置
LOCALE:
  # 加载语言文件的顺序
  PRIORITY:
  - zh_CN
  - en_US
  # 默认是否启用语言文件中 PlaceholderAPI 的替换功能
  # 关闭可提升性能
  # 如果需要开启仍然可以在语言文件中加入 papi: true
  USE_PAPI: false

# 是否注入 PluginManager，关闭后可能会导致部分功能出错。
PLUGIN-INJECTOR:
  ENABLE: true
  # 检测下面的插件并自动关闭注入
  DISABLE-ON-PLUGIN-EXISTS:
  - LuckPerms

# 是否在当前服务器启用交流网终端
# 启用后将会收到大量调试信息, 不建议使用
SERVER: false

# 网络连接测试地址
TEST-URL: 'aliyun.com'

# 下载依赖时启用的线程数
DOWNLOAD-POOL-SIZE: 4

# 玩家列表（TAB-API）是否根据前缀排序
TABLIST-SORT: true

# 玩家列表（TAB-API）是否自动清理没有成员的队伍
TABLIST-AUTO-CLEAN-TEAM: true

# 是否启用更新检测
UPDATE-CHECK: true

# 是否启用自动更新
UPDATE-DOWNLOAD: false

# 是否在关闭服务器时清理玩家数据
# 该配置将在启用数据库储存时失效
DELETE-DATA: false

# 是否在服务器关闭时清理无效变量
# 该配置仅在启用数据库储存时有效
# 该方法可能会导致数据丢失? 
# 不建议开启
DELETE-VARIABLE: false

# 是否以 UUID 的形式创建玩家数据
# 不建议开启！除非用 TabooLib 储存的插件支持新版储存方式！
ENABLE-UUID: false

# 是否隐藏保存数据的提示
HIDE-NOTIFY: true

# 数据库信息
# 该功能在当前版本下无法使用，请勿启用
MYSQL:
  # 是否启用数据库
  ENABLE: false
  # 数据库地址
  HOST: 'localhost'
  # 数据库端口
  PORT: 3306
  # 数据库用户
  USER: root
  # 数据库密码
  PASSWORD: ''
  # 数据库名称
  DATABASE: 'test'
  # 数据表前缀
  PREFIX: 'taboolib'

# 全局变量信息
PluginData:
  # 检查更新间隔（单位：秒）
  # 检查变量是否被其他服务器更新
  CHECK-DELAY: 5